export const adminPage = `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>管理レポート</title><style>
:root{font-family:"Segoe UI",sans-serif;color:#18242c;background:#f3f6f3}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1120px;margin:auto;padding:32px 20px}header{display:flex;justify-content:space-between;align-items:center}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:24px 0}.card,.panel,.login-card{background:white;border:1px solid #dce3dd;border-radius:16px;padding:20px;box-shadow:0 10px 30px #183c3212}.card strong{display:block;font-size:30px}.muted{color:#667780}button{border:0;border-radius:10px;padding:10px 15px;background:#2f6b55;color:white;font-weight:650;cursor:pointer}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #edf0ed}tbody tr{cursor:pointer}.login{position:fixed;inset:0;display:grid;place-items:center;background:#15352d;z-index:5}.login[hidden]{display:none}.login-card{width:min(420px,92vw)}input{width:100%;padding:11px;margin:6px 0;border:1px solid #ccd7cf;border-radius:9px}.error{color:#a33}dialog{border:0;border-radius:16px;width:min(920px,94vw);padding:18px}iframe{width:100%;height:65vh;border:1px solid #ddd}@media(max-width:700px){.cards{grid-template-columns:1fr 1fr}.panel{overflow:auto}}</style></head><body>
<div id="login" class="login"><form id="form" class="login-card"><h1>管理画面ログイン</h1><p class="muted">企業コード、管理者ID、パスワードを入力してください。</p><input id="code" autocomplete="organization" placeholder="企業コード（100文字以内）" maxlength="100" required><input id="email" type="email" autocomplete="username" placeholder="管理者ID（メールアドレス）" required><input id="password" type="password" autocomplete="current-password" placeholder="パスワード" required><button>ログイン</button><p id="error" class="error"></p></form></div>
<main class="wrap"><header><div><p class="muted">Screen Capture Report</p><h1 id="title">企業レポート</h1><p id="fresh" class="muted"></p></div><button id="refresh">更新</button></header><section class="cards"><div class="card">従業員<strong id="employees">—</strong></div><div class="card">週報<strong id="reports">—</strong></div><div class="card">端末<strong id="devices">—</strong></div><div class="card">部署<strong id="departments">—</strong></div></section><section class="panel"><h2>確定週報</h2><table><thead><tr><th>従業員</th><th>部署</th><th>対象期間</th><th>受信日時</th></tr></thead><tbody id="rows"></tbody></table></section></main>
<dialog id="dialog"><button id="close">閉じる</button><p id="hash" class="muted"></p><iframe id="frame" sandbox=""></iframe></dialog><script>
const $=s=>document.querySelector(s);let auth={code:sessionStorage.getItem('scr-company-code')||'',email:sessionStorage.getItem('scr-admin-email')||'',password:sessionStorage.getItem('scr-admin-password')||''},data;
async function api(path){const r=await fetch(path,{headers:{'x-company-code':auth.code,'x-admin-email':auth.email,'x-admin-password':auth.password}});if(!r.ok)throw new Error(String(r.status));return r.json()}
const esc=v=>{const e=document.createElement('span');e.textContent=String(v??'');return e.innerHTML};const date=v=>v?new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
function render(){ $('#title').textContent=(data.company?.name||'企業')+' レポート';$('#fresh').textContent='最終更新 '+date(data.refreshedAt);$('#employees').textContent=data.employees.length;$('#reports').textContent=data.reports.length;$('#devices').textContent=data.employees.reduce((n,x)=>n+Number(x.device_count||0),0);$('#departments').textContent=data.departments.length;$('#rows').innerHTML=data.reports.length?data.reports.map(x=>'<tr data-id="'+esc(x.id)+'"><td>'+esc(x.display_name)+'</td><td>'+esc(x.department)+'</td><td>'+esc(x.period_start)+' ～ '+esc(x.period_end)+'</td><td>'+date(x.received_at)+'</td></tr>').join(''):'<tr><td colspan="4">レポートはまだありません</td></tr>';document.querySelectorAll('tr[data-id]').forEach(r=>r.onclick=()=>openReport(r.dataset.id))}
async function load(){data=await api('/api/admin/summary');render()}async function openReport(id){const x=await api('/api/admin/reports/'+encodeURIComponent(id)+'/content');$('#hash').textContent='SHA-256 '+x.sha256;$('#frame').srcdoc='<meta http-equiv="Content-Security-Policy" content="'+x.csp.replaceAll('"','&quot;')+'">'+x.html;$('#dialog').showModal()}
$('#form').onsubmit=async e=>{e.preventDefault();auth={code:$('#code').value.trim(),email:$('#email').value.trim(),password:$('#password').value};try{await load();for(const [k,v] of Object.entries(auth))sessionStorage.setItem(k==='code'?'scr-company-code':'scr-admin-'+k,v);$('#login').hidden=true}catch{$('#error').textContent='企業コード、ID、またはパスワードが正しくありません'}};$('#refresh').onclick=load;$('#close').onclick=()=>$('#dialog').close();if(auth.code&&auth.email&&auth.password)load().then(()=>$('#login').hidden=true).catch(()=>{});
</script></body></html>`;
