export const dashboardPage = `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="WORK VISIBILITY AI AI化トランスフォーメーション">
  <title>WORK VISIBILITY AI — AI化トランスフォーメーション</title>
  <style>
    :root{color-scheme:light;--navy:#20264f;--navy2:#2d356a;--blue:#2b52d4;--blue-soft:#eef2fd;--ink:#171a23;--muted:#737989;--canvas:#f4f5f7;--paper:#fff;--line:#e0e3e9;--green:#16815f;--green-soft:#e8f5f0;--amber:#b86d12;--amber-soft:#fff3df;--shadow:0 12px 34px rgba(28,33,67,.07);--radius:16px}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--canvas);color:var(--ink);font-family:Inter,"Noto Sans JP","Yu Gothic UI","Segoe UI",sans-serif;font-size:14px;line-height:1.55}button,select{font:inherit}button{cursor:pointer}.num{font-variant-numeric:tabular-nums}
    .app{display:grid;grid-template-columns:260px minmax(0,1fr);min-height:100vh}.sidebar{background:var(--navy);color:#fff;padding:26px 18px 20px;position:sticky;top:0;height:100vh;display:flex;flex-direction:column;z-index:20}.brand{display:flex;align-items:center;gap:11px;padding:0 10px 28px;font-size:16px;font-weight:800}.brand-mark{width:30px;height:30px;border-radius:8px;background:#fff;color:var(--navy);display:grid;place-items:center;font-size:11px}.brand-name small{display:block;color:#aeb6dd;font-size:10px;letter-spacing:.04em;margin-top:2px}.nav-label{padding:17px 12px 7px;color:#929bc7;font-size:10px;font-weight:800;letter-spacing:.18em}.nav button{border:0;width:100%;display:flex;align-items:center;gap:12px;padding:11px 13px;border-radius:10px;color:#d8dcf3;background:transparent;text-align:left;font-weight:650;margin:2px 0}.nav button:hover,.nav button.active{background:#fff;color:var(--navy)}.nav svg{width:17px;height:17px;stroke:currentColor;fill:none;stroke-width:1.8}.side-note{margin-top:auto;padding:15px;border:1px solid rgba(255,255,255,.13);border-radius:12px;background:rgba(255,255,255,.06);color:#bec4e4;font-size:11px}.side-note b{color:#fff;display:block;margin-bottom:3px}.side-user{display:flex;align-items:center;gap:10px;margin-top:13px;padding:12px 8px 0}.avatar{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#eef0ff;color:var(--navy);font-weight:800}.side-user small{display:block;color:#9ca5d1}.content{min-width:0}.topbar{height:74px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 34px;position:sticky;top:0;z-index:10}.breadcrumb{color:var(--muted);font-size:12px}.breadcrumb b{color:var(--ink);font-size:16px;display:block}.system-state{display:flex;align-items:center;gap:9px;color:var(--muted);font-weight:650}.dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 0 5px var(--green-soft)}.icon-button{width:34px;height:34px;border-radius:9px;border:1px solid var(--line);background:#fff;color:var(--navy);display:grid;place-items:center}.mobile-toggle{display:none}
    .main{padding:30px 34px 56px;max-width:1500px;margin:auto}.page-head{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;margin-bottom:18px}.kicker{font-size:10px;color:var(--blue);font-weight:850;letter-spacing:.2em;text-transform:uppercase}.page-head h1{font-size:28px;letter-spacing:-.035em;margin:5px 0 4px}.page-head p{margin:0;color:var(--muted)}.filters{display:flex;gap:9px;flex-wrap:wrap}.select{background:#fff;border:1px solid var(--line);border-radius:10px;padding:9px 34px 9px 12px;color:#3d4352}
    .transformation{background:#fff;border:1px solid var(--line);border-radius:20px;padding:26px;box-shadow:var(--shadow)}.transformation-head{max-width:760px}.transformation-head h2{font-size:clamp(25px,3vw,38px);line-height:1.3;letter-spacing:-.035em;margin:7px 0}.transformation-head h2 span{color:var(--blue)}.transformation-head p{color:var(--muted);margin:0}.summary{background:var(--navy);color:#fff;border-radius:15px;padding:21px 24px;margin:22px 0 14px;display:flex;justify-content:space-between;align-items:center;gap:20px}.summary small{color:#aeb6dc;font-weight:700;letter-spacing:.08em}.summary b{display:block;margin-top:4px}.summary-value{text-align:right}.summary-value strong{font-size:clamp(32px,4vw,48px);letter-spacing:-.05em}.summary-value strong span{font-size:17px;color:#aeb6dc;margin-left:4px}.summary-value div{font-size:11px;color:#aeb6dc}.meta{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:17px}.chip{border:1px solid var(--line);border-radius:999px;padding:6px 11px;color:var(--muted);font-size:11px}.chip b{color:var(--ink)}.chip.warning{border-color:#efd9b8;background:#fffaf2;color:var(--amber)}.chip.warning b{color:var(--amber)}
    .scenario-list{border:1px solid var(--line);border-radius:14px;overflow:hidden}.scenario-row{display:grid;grid-template-columns:110px minmax(180px,1fr) 90px 180px 90px 110px;align-items:center;gap:10px;padding:13px 16px;border-bottom:1px solid var(--line)}.scenario-row:last-child{border-bottom:0}.scenario-row.header{background:#fafbfc;min-height:42px;padding-top:9px;padding-bottom:9px;color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.07em}.dept{font-size:11px;color:var(--muted)}.task b{display:block;font-size:13px}.task small{color:var(--muted)}.hours{text-align:right}.hours b{font-size:18px}.hours small{color:var(--muted)}.ai-pill{background:var(--blue-soft);color:var(--blue);border-radius:9px;padding:8px 10px;text-align:center;font-size:12px;font-weight:750}.after b,.saving b{color:var(--green)}.saving{text-align:right}.saving span{display:block;background:var(--green-soft);color:var(--green);font-size:10px;font-weight:800;border-radius:999px;padding:3px 7px;margin-top:3px}.details-button{border:1px solid var(--line);background:#fff;color:var(--navy);border-radius:9px;padding:7px 9px;font-size:11px;font-weight:750}.details-button:hover,.details-button:focus-visible{border-color:var(--blue);outline:3px solid var(--blue-soft)}.scenario-row.extra{display:none}.scenario-list.expanded .scenario-row.extra{display:grid}.expand-row{display:flex;justify-content:center;margin:14px 0 2px}.expand-button{border:1px solid var(--line);background:#fff;color:var(--navy);border-radius:10px;padding:9px 16px;font-weight:750}.recover{background:var(--blue-soft);border:1px solid #d7e0fb;border-radius:13px;padding:14px 16px;margin-top:15px;color:var(--muted);font-size:12px}.recover b{color:var(--blue)}.disclaimer{font-size:11px;color:var(--muted);margin:13px 0 0}.disclaimer strong{color:var(--amber)}
    .lower{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.panel{background:#fff;border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);overflow:hidden}.panel-head{padding:17px 19px 13px}.panel h3{font-size:15px;margin:0}.panel-sub{font-size:11px;color:var(--muted)}.quality-grid{padding:4px 19px 19px;display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.quality-card{padding:12px;background:#f7f8fa;border-radius:10px}.quality-card span{display:block;color:var(--muted);font-size:10px}.quality-card b{font-size:18px}.operation-list{padding:0 19px 15px}.operation{display:flex;justify-content:space-between;align-items:center;padding:12px 0;border-top:1px solid var(--line)}.operation b{display:block;font-size:12px}.operation small{color:var(--muted)}.badge{border-radius:999px;background:var(--green-soft);color:var(--green);padding:4px 8px;font-size:10px;font-weight:800}.badge.warn{background:var(--amber-soft);color:var(--amber)}
    dialog{border:0;padding:0;width:min(520px,92vw);border-radius:17px;box-shadow:0 30px 90px rgba(20,24,52,.28)}dialog::backdrop{background:rgba(15,18,40,.55)}.dialog-head{display:flex;justify-content:space-between;align-items:flex-start;padding:20px 22px;border-bottom:1px solid var(--line)}.dialog-head h3{margin:4px 0 0;font-size:20px}.dialog-close{width:35px;height:35px;border:1px solid var(--line);background:#fff;border-radius:9px}.dialog-body{padding:20px 22px}.dialog-metrics{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin:14px 0}.dialog-metric{background:#f6f7f9;border-radius:10px;padding:10px}.dialog-metric span{display:block;font-size:9px;color:var(--muted)}.dialog-metric b{font-size:17px}.formula{background:var(--blue-soft);border-left:3px solid var(--blue);padding:12px;font-size:12px;color:#586078}.dialog-actions{padding-left:18px;color:#586078}.toast{position:fixed;left:50%;bottom:24px;transform:translate(-50%,30px);background:#171a23;color:#fff;border-radius:10px;padding:10px 14px;opacity:0;transition:.2s;z-index:50}.toast.show{opacity:1;transform:translate(-50%,0)}
    @media(max-width:1080px){.scenario-row{grid-template-columns:95px minmax(160px,1fr) 75px 150px 75px 95px}.lower{grid-template-columns:1fr}}
    @media(max-width:960px){.scenario-row.header{display:none}.scenario-row,.scenario-list.expanded .scenario-row.extra{grid-template-columns:1fr 1fr;gap:8px 12px;padding:15px;border-bottom:6px solid var(--canvas)}.scenario-row .dept,.scenario-row .task{grid-column:1/-1}.hours{text-align:left}.hours:before,.after:before,.saving:before{display:block;color:var(--muted);font-size:9px}.hours:before{content:"現状（デモ値）"}.after:before{content:"導入後（試算）"}.saving:before{content:"削減予想"}.saving{text-align:left}.details-button{grid-column:1/-1}.summary{align-items:flex-start}}
    @media(max-width:780px){.app{grid-template-columns:1fr}.sidebar{position:fixed;left:0;transform:translateX(-105%);transition:.25s;width:260px}.sidebar.open{transform:none}.mobile-toggle{display:grid}.topbar{height:64px;padding:0 16px}.system-state{display:none}.main{padding:22px 15px 48px}.page-head{display:block}.filters{margin-top:13px}.transformation{padding:19px}.quality-grid{grid-template-columns:1fr 1fr}}
    @media(max-width:520px){.summary{display:block}.summary-value{text-align:left;margin-top:15px}.scenario-row,.scenario-list.expanded .scenario-row.extra{grid-template-columns:1fr}.scenario-row .dept,.scenario-row .task,.details-button{grid-column:auto}.ai-pill{text-align:left}.quality-grid{grid-template-columns:1fr}.dialog-metrics{grid-template-columns:1fr}}
  </style>
</head>
<body>
<div class="app">
  <aside class="sidebar" id="sidebar">
    <div class="brand"><span class="brand-mark">WV</span><span class="brand-name">WORK VISIBILITY AI<small>株式会社ライトアップ</small></span></div>
    <nav class="nav" aria-label="メインナビゲーション">
      <div class="nav-label">OVERVIEW</div>
      <button class="active" data-view="transformation"><svg viewBox="0 0 24 24"><path d="m12 3 1.7 4.3L18 9l-4.3 1.7L12 15l-1.7-4.3L6 9l4.3-1.7z"/></svg>AI化トランスフォーメーション</button>
      <button data-view="dashboard"><svg viewBox="0 0 24 24"><path d="M3 11 12 3l9 8v9H3z"/><path d="M9 20v-6h6v6"/></svg>業務ダッシュボード</button>
      <div class="nav-label">GOVERNANCE</div>
      <button data-view="operations"><svg viewBox="0 0 24 24"><rect x="4" y="3" width="16" height="13" rx="2"/><path d="M9 21h6m-3-5v5"/></svg>運用状況</button>
    </nav>
    <div class="side-note"><b>監視ではなく、可視化。</b>生画像・ウィンドウタイトル・個人ランキングは管理画面に表示しません。</div>
    <div class="side-user"><span class="avatar">MO</span><span><b>岡村 正弘</b><small>経営管理者</small></span></div>
  </aside>
  <div class="content">
    <header class="topbar"><div style="display:flex;align-items:center;gap:12px"><button class="icon-button mobile-toggle" id="menu" aria-label="メニュー">☰</button><div class="breadcrumb">A-02<b>AI化トランスフォーメーション</b></div></div><div class="system-state"><span class="dot"></span>全システム正常</div></header>
    <main class="main">
      <section class="page-head"><div><div class="kicker">Management overview</div><h1>AI化トランスフォーメーション</h1><p>可視化で終わらせず、実行できるAI化の処方箋へ。</p></div><div class="filters"><select class="select" id="period" aria-label="対象期間"><option>2026年7月</option><option>2026年6月</option></select><select class="select" id="department" aria-label="対象部署"><option>全社</option><option>営業部</option><option>マーケ部</option><option>管理部</option></select></div></section>
      <section class="transformation">
        <div class="transformation-head"><div class="kicker">AI transformation</div><h2>この作業を、<span>このAIで</span>、こう変える。</h2><p>業務ログをもとにしたデモシナリオへ対応するAIを当てた場合の削減予想です。可視化が診断なら、ここから先が処方箋です。</p></div>
        <div class="summary"><div><small>10名分のデモシナリオ / 合計月間</small><b>対象業務をAI化した場合の削減予想</b></div><div class="summary-value"><strong class="num">−134.3<span>h / 月</span></strong><div>現状169.3時間 → 導入後35.0時間（試算）</div></div></div>
        <div class="meta"><span class="chip">対象期間 <b>2026年7月換算</b></span><span class="chip">対象 <b>10名相当のデモシナリオ</b></span><span class="chip warning">数値は<b>すべてデモ用想定値</b></span></div>
        <div class="scenario-list" id="scenarioList">
          <div class="scenario-row header"><div>部署</div><div>対象業務</div><div style="text-align:right">現状 / 月</div><div style="text-align:center">推奨AI</div><div style="text-align:right">導入後</div><div style="text-align:right">削減予想</div></div>
          <div class="scenario-row"><div class="dept">営業部</div><div class="task"><b>会議の議事録作成・共有</b><small>対象1名相当</small></div><div class="hours"><b class="num">26.0h</b></div><div class="ai-pill">議事録AI<br><small>文字起こし＋要約</small></div><div class="hours after"><b class="num">2.0h</b></div><div class="saving"><b class="num">−24.0h</b><span>92%減</span><button class="details-button" data-scenario="0">根拠を見る</button></div></div>
          <div class="scenario-row"><div class="dept">営業部</div><div class="task"><b>提案書・営業資料の作成</b><small>対象1名相当</small></div><div class="hours"><b class="num">22.5h</b></div><div class="ai-pill">資料作成AI<br><small>初稿の自動生成</small></div><div class="hours after"><b class="num">6.0h</b></div><div class="saving"><b class="num">−16.5h</b><span>73%減</span><button class="details-button" data-scenario="1">根拠を見る</button></div></div>
          <div class="scenario-row"><div class="dept">マーケ部</div><div class="task"><b>SNSの投稿・運用</b><small>対象1名相当</small></div><div class="hours"><b class="num">18.0h</b></div><div class="ai-pill">SNS運用AI<br><small>投稿・反応の自動化</small></div><div class="hours after"><b class="num">2.0h</b></div><div class="saving"><b class="num">−16.0h</b><span>89%減</span><button class="details-button" data-scenario="2">根拠を見る</button></div></div>
          <div class="scenario-row extra"><div class="dept">営業部</div><div class="task"><b>定型メールの返信</b><small>対象1名相当</small></div><div class="hours"><b class="num">16.8h</b></div><div class="ai-pill">メール返信AI<br><small>下書き自動生成</small></div><div class="hours after"><b class="num">4.0h</b></div><div class="saving"><b class="num">−12.8h</b><span>76%減</span><button class="details-button" data-scenario="3">根拠を見る</button></div></div>
          <div class="scenario-row extra"><div class="dept">管理部</div><div class="task"><b>データ入力・転記</b><small>対象1名相当</small></div><div class="hours"><b class="num">20.0h</b></div><div class="ai-pill">転記AI<br><small>OCR＋自動転記</small></div><div class="hours after"><b class="num">3.0h</b></div><div class="saving"><b class="num">−17.0h</b><span>85%減</span><button class="details-button" data-scenario="4">根拠を見る</button></div></div>
          <div class="scenario-row extra"><div class="dept">IS部</div><div class="task"><b>電話の一次対応</b><small>対象1名相当</small></div><div class="hours"><b class="num">14.0h</b></div><div class="ai-pill">電話応対AI<br><small>一次受け・要約</small></div><div class="hours after"><b class="num">5.0h</b></div><div class="saving"><b class="num">−9.0h</b><span>64%減</span><button class="details-button" data-scenario="5">根拠を見る</button></div></div>
          <div class="scenario-row extra"><div class="dept">営業部</div><div class="task"><b>見積書の作成</b><small>対象1名相当</small></div><div class="hours"><b class="num">12.5h</b></div><div class="ai-pill">見積作成AI<br><small>項目の自動起票</small></div><div class="hours after"><b class="num">3.5h</b></div><div class="saving"><b class="num">−9.0h</b><span>72%減</span><button class="details-button" data-scenario="6">根拠を見る</button></div></div>
          <div class="scenario-row extra"><div class="dept">マーケ部</div><div class="task"><b>問い合わせ・FAQ対応</b><small>対象1名相当</small></div><div class="hours"><b class="num">15.5h</b></div><div class="ai-pill">問い合わせ対応AI<br><small>一次回答の自動化</small></div><div class="hours after"><b class="num">4.5h</b></div><div class="saving"><b class="num">−11.0h</b><span>71%減</span><button class="details-button" data-scenario="7">根拠を見る</button></div></div>
          <div class="scenario-row extra"><div class="dept">営業部</div><div class="task"><b>顧客リストの精査・整理</b><small>対象1名相当</small></div><div class="hours"><b class="num">11.0h</b></div><div class="ai-pill">リスト精査AI<br><small>名寄せ・優先度付け</small></div><div class="hours after"><b class="num">2.0h</b></div><div class="saving"><b class="num">−9.0h</b><span>82%減</span><button class="details-button" data-scenario="8">根拠を見る</button></div></div>
          <div class="scenario-row extra"><div class="dept">人事部</div><div class="task"><b>採用スカウト文の作成</b><small>対象1名相当</small></div><div class="hours"><b class="num">13.0h</b></div><div class="ai-pill">スカウト文AI<br><small>個別文面の自動生成</small></div><div class="hours after"><b class="num">3.0h</b></div><div class="saving"><b class="num">−10.0h</b><span>77%減</span><button class="details-button" data-scenario="9">根拠を見る</button></div></div>
        </div>
        <div class="expand-row"><button class="expand-button" id="expandScenarios" aria-expanded="false">10件すべて表示</button></div>
        <div class="recover"><b>上記のAIは、すべてライトアップが提供します。</b> 可視化で見つけた業務に、導入・伴走までご提案します。</div>
        <p class="disclaimer"><strong>※ 本画面はデモ用モックです。</strong> 時間・削減率はすべて想定値であり、実導入時は初月の実測ログで補正します。業務改善のための集計であり、個人の勤務態度の評価には使用しません。</p>
      </section>
      <section class="lower">
        <article class="panel"><div class="panel-head"><h3>データ品質</h3><div class="panel-sub">本番データ接続時に必ず表示する判断の前提</div></div><div class="quality-grid"><div class="quality-card"><span>対象人数</span><b>10名相当</b></div><div class="quality-card"><span>数値区分</span><b>デモ値</b></div><div class="quality-card"><span>本番補正</span><b>初月実測後</b></div></div></article>
        <article class="panel"><div class="panel-head"><h3>運用上の要対応</h3><div class="panel-sub">導入前に確認する事項</div></div><div class="operation-list"><div class="operation"><span><b>実データへの差し替え</b><small>期間・取得率・分析信頼度を付与</small></span><span class="badge warn">要対応</span></div><div class="operation"><span><b>プライバシー境界</b><small>生画像・個人ランキングなし</small></span><span class="badge">適用中</span></div></div></article>
      </section>
    </main>
  </div>
</div>
<dialog id="scenarioDialog"><div class="dialog-head"><div><div class="kicker">Scenario detail</div><h3 id="dialogTitle">AI化シナリオ</h3></div><button class="dialog-close" id="dialogClose" aria-label="閉じる">×</button></div><div class="dialog-body"><p id="dialogDescription"></p><div class="dialog-metrics"><div class="dialog-metric"><span>現状（デモ値）</span><b id="dialogBefore"></b></div><div class="dialog-metric"><span>導入後（試算）</span><b id="dialogAfter"></b></div><div class="dialog-metric"><span>削減予想</span><b id="dialogSaving"></b></div></div><div class="formula" id="dialogFormula"></div><h4>次のアクション</h4><ol class="dialog-actions"><li>対象業務と例外処理を棚卸し</li><li>2週間の小規模PoCで精度を検証</li><li>導入前後の実測時間を比較</li></ol></div></dialog>
<div class="toast" id="toast" role="status"></div>
<script>
const scenarios=[
['会議の議事録作成・共有','議事録AI','26.0','2.0','24.0','92'],['提案書・営業資料の作成','資料作成AI','22.5','6.0','16.5','73'],['SNSの投稿・運用','SNS運用AI','18.0','2.0','16.0','89'],['定型メールの返信','メール返信AI','16.8','4.0','12.8','76'],['データ入力・転記','転記AI','20.0','3.0','17.0','85'],['電話の一次対応','電話応対AI','14.0','5.0','9.0','64'],['見積書の作成','見積作成AI','12.5','3.5','9.0','72'],['問い合わせ・FAQ対応','問い合わせ対応AI','15.5','4.5','11.0','71'],['顧客リストの精査・整理','リスト精査AI','11.0','2.0','9.0','82'],['採用スカウト文の作成','スカウト文AI','13.0','3.0','10.0','77']];
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];function toast(message){const el=q('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2000)}
q('#expandScenarios').onclick=()=>{const list=q('#scenarioList');const expanded=!list.classList.contains('expanded');list.classList.toggle('expanded',expanded);q('#expandScenarios').textContent=expanded?'上位3件のみ表示':'10件すべて表示';q('#expandScenarios').setAttribute('aria-expanded',String(expanded))};
qa('[data-scenario]').forEach(button=>button.onclick=()=>{const s=scenarios[Number(button.dataset.scenario)];q('#dialogTitle').textContent=s[0];q('#dialogDescription').textContent=s[1]+'を適用した場合のデモ試算です。';q('#dialogBefore').textContent=s[2]+'h';q('#dialogAfter').textContent=s[3]+'h';q('#dialogSaving').textContent='−'+s[4]+'h';q('#dialogFormula').textContent='現状 '+s[2]+'h − 導入後 '+s[3]+'h = 削減予想 '+s[4]+'h / 月（'+s[5]+'%減）';q('#scenarioDialog').showModal()});
q('#dialogClose').onclick=()=>q('#scenarioDialog').close();q('#scenarioDialog').onclick=e=>{if(e.target===q('#scenarioDialog'))q('#scenarioDialog').close()};q('#menu').onclick=()=>q('#sidebar').classList.toggle('open');qa('.nav button').forEach(button=>button.onclick=()=>{qa('.nav button').forEach(x=>x.classList.remove('active'));button.classList.add('active');q('#sidebar').classList.remove('open');toast(button.textContent.trim()+'を選択しました')});q('#period').onchange=()=>toast('対象期間を更新しました');q('#department').onchange=()=>toast(q('#department').value+'で絞り込みました');
</script>
</body></html>`;
